# Jivelite makefile

PREFIX ?= /Users/paddockd/source/jivelite

all: srcs libs

srcs:
	tar -xzf scripts/buildosx-include.tar.gz
	tar -xzf scripts/buildosx-lib.tar.gz
	cd src; PREFIX=$(PREFIX) make -f Makefile.x86_64

libs: lib/lua

lib/lua:
	cd lib-src; PREFIX=$(PREFIX) make -f Makefile.x86_64

clean:
	rm -Rf lib include
	cd src; make clean
	cd lib-src; PREFIX=$(PREFIX) make -f Makefile.x86_64 clean

