# Jivelite makefile

PREFIX ?= /usr/local

all: srcs libs

srcs:
	cd src; PREFIX=$(PREFIX) make -f Makefile.osx

libs: lib

lib:
	cd lib-src; PREFIX=$(PREFIX) make -f Makefile.osx

clean:
	rm -Rf lib
	cd src; make -f Makefile.osx clean
	cd lib-src; make -f Makefile.osx clean

