# makefile wrapper for osx

# this is only needed if SDL is installed in /usr/local
CFLAGS += -I$(PREFIX)/include/SDL -I$(PREFIX)/include

LDFLAGS += -L$(PREFIX)/lib -lz -ljpeg -lpng -lpng12 -lfreetype -lSDLmain -lresolv -Wl,-framework,OpenGL -Wl,-framework,Cocoa -Wl,-framework,ApplicationServices -Wl,-framework,Carbon -Wl,-framework,AudioToolbox -Wl,-framework,AudioUnit -Wl,-framework,IOKit

SOURCES = platform_osx.c

include Makefile
